package softuni.springadvanced.models.entity;

public enum RoomType {
    DOUBLE, STUDIO, ONE_BEDROOM_APARTMENT, TWO_BEDROOM_APARTMENT,
    DOUBLE_DELUXE, STUDIO_DELUXE, ONE_BEDROOM_APARTMENT_DELUXE, TWO_BEDROOM_APARTMENT_DELUXE
}
